apiVersion: v1
kind: ConfigMap
metadata:
  name: nm2-grafana-datasources
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nm2.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://nm2-prometheus.{{ .Values.global.namespace }}.svc:{{ .Values.prometheus.port }}
        access: proxy
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 30s

      - name: nm2-postgres
        type: postgres
        url: nm2-postgres.{{ .Values.global.namespace }}.svc:{{ .Values.postgres.port }}
        database: {{ .Values.secrets.postgres.database }}
        user: {{ .Values.secrets.grafana.dbUser }}
        secureJsonData:
          password: {{ .Values.secrets.grafana.dbPassword }}
        jsonData:
          sslmode: disable
          postgresVersion: 1600
          timescaledb: false
        isDefault: false
        editable: true
