apiVersion: v1
kind: Service
metadata:
  name: nm2-grafana
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nm2.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: nm2-grafana
  ports:
    - port: {{ .Values.grafana.port }}
      targetPort: {{ .Values.grafana.port }}
  type: ClusterIP
