apiVersion: apps/v1
kind: Deployment
metadata:
  name: nm2-prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nm2.labels" . | nindent 4 }}
    app.kubernetes.io/name: nm2-prometheus
spec:
  replicas: {{ .Values.prometheus.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nm2-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nm2-prometheus
    spec:
      serviceAccountName: nm2-prometheus
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
        runAsNonRoot: true
      containers:
        - name: prometheus
          image: {{ .Values.prometheus.image }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time={{ .Values.prometheus.retention }}"
            - "--web.enable-lifecycle"
            {{- if .Values.prometheus.remoteWriteReceiver }}
            - "--web.enable-remote-write-receiver"
            {{- end }}
          ports:
            - containerPort: {{ .Values.prometheus.port }}
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
              readOnly: true
            - name: data
              mountPath: /prometheus
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /-/ready
              port: {{ .Values.prometheus.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: {{ .Values.prometheus.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: nm2-prometheus-config
        - name: data
          persistentVolumeClaim:
            claimName: nm2-prometheus-data
