apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nm2-prometheus-data
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nm2.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.prometheus.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.size }}
